print('Welcome to the Program! Please enter the value of A, B, C and X at the corresponding prompts')
A = int(input('What is the value of A? '))
B = int(input('What is the value of B? '))
C = int(input('What is the value of C? '))
X = int(input('What is the value of X? '))
print('The following quadratic was entered:', A+'X'+'^2 + 'B+''*X + C')